# ----------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, 
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
# OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
# ----------------------------------------------------------------------------------

variables:

  deploymentRegion: canadacentral
  serviceConnection: sp-eslz-bcamp # spn-azure-platform-ops
  vmImage: ubuntu-latest
  deployOperation: create  # valid options: 'create', 'what-if'
  subscriptionsPathFromRoot: 'config/subscriptions'
  var-bashPreInjectScript: 'set -E; function catch { echo "##vso[task.logissue type=error]Caller: $(caller), LineNo: $LINENO, Command: $BASH_COMMAND" ; exit 1 ; } ; echo ; echo "Current working directory: $(pwd)" ; echo ; trap catch ERR'
  var-bashPostInjectScript: ':'
  var-TriggerSubscriptionDeployOn: 'A'  # A=added, M=modified, D=deleted
